theme: jekyll-theme-cayman
facebook:
  username: Steve Bell;
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /kasaSocialPreview.jpg
        height: 630
        width: 1200
google_analytics: UA-118642689-4
